In [1]:
# Package(s) Import and Path Setting

In [2]:
import os 
import numpy as np
import pandas as pd
import pymysql as pysql
import pymysql.cursors 
os.chdir('/home/pranathi/Documents/RPySADBE/Python/Chapter_02')

In [3]:
# Simple Operations

In [4]:
x = 8
y = 15
a = 10
b = -4
a,b=10,-4 # equivalently
x + y

23

In [5]:
a*x + b*y

20

In [6]:
(a+b)*x == a*x + b*x

True

In [7]:
x*y

120

In [8]:
round(x/y,4)

0.5333

In [9]:
x**2

64

In [10]:
# Python Vectors

In [11]:
x = np.array([1,4,3])
y = np.array([2,9,14])
x+y

array([ 3, 13, 17])

In [12]:
x-y

array([ -1,  -5, -11])

In [13]:
x*y

array([ 2, 36, 42])

In [14]:
x/y

array([ 0.5       ,  0.44444444,  0.21428571])

In [15]:
x-[1,2,3,4]

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [16]:
np.dot(x,y)

80

In [17]:
np.sqrt((x*x).sum())

5.0990195135927845

In [18]:
# Equivalently
np.sqrt(sum(x*x))

5.0990195135927845

In [19]:
# Python Matrix

In [20]:
X = np.array([[10,20,30],[5,16,28],[8,2,19]])
Y = np.array([4,5,9])
X+45

array([[55, 65, 75],
       [50, 61, 73],
       [53, 47, 64]])

In [21]:
np.transpose(X)

array([[10,  5,  8],
       [20, 16,  2],
       [30, 28, 19]])

In [22]:
np.cross(X,Y)

array([[ 30,  30, -30],
       [  4,  67, -39],
       [-77,   4,  32]])

In [23]:
np.cross(np.linalg.inv(np.cross(np.transpose(X),X)),np.cross(np.transpose(X),Y))

array([[ 0.04380446,  0.19653758,  0.37267192],
       [-0.30138658, -0.06915852,  0.79140376],
       [-0.51307144, -0.40652873,  0.04435901]])

In [24]:
# Importing CSV Files and Merging

In [25]:
SCV = pd.read_csv("Data/SCV.csv")
SCV.shape
print(SCV)

    Response   A   B    C    D         E
0         47   8  50  0.2  0.4     Usual
1         42   8  50  0.4  0.4  Modified
2         50   8  60  0.4  0.4     Usual
3         51   8  60  0.2  0.4  Modified
4         40  16  50  0.4  0.4     Usual
5         44  16  50  0.2  0.4  Modified
6         46  16  60  0.2  0.4     Usual
7         40  16  60  0.4  0.4  Modified
8         28   8  50  0.2  0.6     Usual
9         23   8  50  0.4  0.6  Modified
10        30   8  60  0.4  0.6     Usual
11        38   8  60  0.2  0.6  Modified
12        26  16  50  0.4  0.6     Usual
13        31  16  50  0.2  0.6  Modified
14        32  16  60  0.2  0.6     Usual
15        33  16  60  0.4  0.6  Modified


In [26]:
SCV_M = pd.read_csv("Data/SCV_Modified.csv")
SCV_U = pd.read_csv("Data/SCV_Usual.csv")
comb_scv = [SCV_M,SCV_U]
SCV_Combined = pd.concat(comb_scv)
SCV_Combined

Response   A   B    C    D         E
0        42   8  50  0.4  0.4  Modified
1        51   8  60  0.2  0.4  Modified
2        44  16  50  0.2  0.4  Modified
3        40  16  60  0.4  0.4  Modified
4        23   8  50  0.4  0.6  Modified
5        38   8  60  0.2  0.6  Modified
6        31  16  50  0.2  0.6  Modified
7        33  16  60  0.4  0.6  Modified
0        47   8  50  0.2  0.4     Usual
1        50   8  60  0.4  0.4     Usual
2        40  16  50  0.4  0.4     Usual
3        46  16  60  0.2  0.4     Usual
4        28   8  50  0.2  0.6     Usual
5        30   8  60  0.4  0.6     Usual
6        26  16  50  0.4  0.6     Usual
7        32  16  60  0.2  0.6     Usual

In [27]:
# Connecting with MySQL

In [28]:
connection = pysql.connect(host="localhost",user='root',password='statmath',
                          db='test',cursorclass=pymysql.cursors.DictCursor)
cur = connection.cursor()
cur.execute("SELECT * FROM IO_Time")
print(cur.description)
for row in cur:
    print(row)
cur.close()
connection.close()

(('No_of_IO', 3, None, 9, 9, 0, True), ('CPU_Time', 4, None, 12, 12, 31, True))
{'No_of_IO': 1, 'CPU_Time': 0.092}
{'No_of_IO': 2, 'CPU_Time': 0.134}
{'No_of_IO': 3, 'CPU_Time': 0.165}
{'No_of_IO': 4, 'CPU_Time': 0.211}
{'No_of_IO': 5, 'CPU_Time': 0.242}
{'No_of_IO': 6, 'CPU_Time': 0.302}
{'No_of_IO': 7, 'CPU_Time': 0.357}
{'No_of_IO': 8, 'CPU_Time': 0.401}
{'No_of_IO': 9, 'CPU_Time': 0.405}
{'No_of_IO': 10, 'CPU_Time': 0.442}


In [1]:
whos

Interactive namespace is empty.
